# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02cd8ae7feabf1537c9e8d555aa78022bae4b54d0e1b33dc291bd139c1a682a6b9d500d0853ca543cb7774e7f946526d3d2776c7b4eebbf8b6d2fbd28379e368

test:
  secret_key_base: 21b74b830b87234f2384dc33d03dcde2b5221452c61be381812a9334b0a1004d9896108861326139ffaf558be4df8911020a1bcf5a9ae14e2a65ae35338d6edb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
